apiVersion: v1
kind: Service
metadata:
  name: nodejs-kube-app-service
spec:
  selector:
    app: nodejs-kube-app
  ports:
    - protocol: TCP
      port: 80  # 外部访问的端口
      targetPort: 3000  # 容器内部应用运行的端口
  type: LoadBalancer
